require:
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'

Metrics/MethodLength:
  Max: 20

Naming/InclusiveLanguage:
  Enabled: True
